/* eslint-disable no-dupe-keys */
// eslint-disable-next-line import/no-anonymous-default-export
export default {
  welcome: 'Welcome to React Native DeHR by TheCodingMachine',
  actions: {
    continue: 'Continue'
  },
  common: {
    error: 'Error',
    empty: 'Empty',
    copy: 'Copy',
    share: 'Share',
    success: 'SUCCESS',
    comming_soon: 'Comming Soon',
    process: 'Processing',
    process_toast: 'Processing! Wait for acceptance'
  },
  login: {
    login: 'Login',
    register: 'Register',
    dont_account: 'Don’t have account?',
    forgot_pass: 'Forgot \nPassword?',
    forgot_hint: 'Enter the email address associated with your account',
    forgot_pass_button: 'Forgot Password?',
    email_wrong: 'Email Wrong!',
    confirm: 'Comfirm',
    welcome: 'Welcome \nBack!',
    password_length: 'Password minimum 6!',
    user_lenght: 'UserName minimum 3!',
    verify_email: 'Verify\nYour Email',
    four_code: 'Please enter the 4 digit code sent to ',
    resend_code: 'Resend code',
    create_pass: 'Create New Password!',
    new_pass: 'New Password',
    verify_pass: 'Verify password',
    create_now: 'Create now',
    create_acc: 'Create \nAccount!',
    have_account: 'Already have account?',
    term1: 'By clicking Register, you agree to ',
    term2: 'DeHR’s User Agreement ',
    term3: ', Privacy Policy, and Cookie Policy.',
    verify_now: 'Verify now',
    verify_account: 'Verify account',
    confirm_email: 'Please wait for confirmation from',
    send_link: 'The activation link has sent to your email!',
    verify_checksum_error:
      'Your account is not available, Please check your account infomation again',
    register_active:
      'We have sent an email with a confirmation link to your email address. In order to complete the sign-up process, please click the confirmation link.'
  },
  chat: {
    mesage: 'Message',
    new_message: 'New Message',
    chat_bot: 'Alecta',
    search_conversation: 'Search for messages or users',
    write_to_message: 'Write a message',
    search_user: 'Type a name',
    to_search: 'To:',
    my_network: 'Networks',
    recommend: 'Recommend',
    requested: 'Requested'
  },
  profile: {
    welcome: 'Welcome {{name}}!',
    welcome_des: 'Connect with people and employer\neverywhere. Earn DeHR coin and more',
    create_profile: 'Create Profile',
    your_profile: 'Your Profile',
    intro: 'Intro',
    headline: 'Headline',
    enter_headline: 'Enter a headline',
    current_position: 'Current Position',
    choose_position: 'Choose your position',
    location: 'Location',
    choose_location: 'Choose your location',
    industrial_knowledge: 'Industrial Knowledge',
    choose_industrial_knowledge: 'Choose your Industrial Knowledge',
    about: 'About',
    summary: 'Summary',
    summary_des: 'Use summary to share what you do or\nthe opportunities you’re looking for',
    background: 'Background',
    experience: 'Experience',
    experience_des: 'Showcase your experience',
    education: 'Education',
    education_des: 'Highlight your education',
    skills: 'Skills',
    specialist_skills: 'Specialist Skills',
    specialist_skills_des: 'Skills on your profile',
    languages: 'Languages',
    languages_des: 'Choose your languages',
    other_skills: 'Other skills',
    other_skills_des: 'Choose your other skills',
    additional_infor: 'Additional Information',
    site_company: 'Site Company',
    site_company_des: 'Your site company',
    hobbies: 'Hobbies',
    hobbies_des: 'Your hobbies',
    social_links: 'Social links',
    social_links_des: 'Your social links',
    save: 'Save',
    enter_summary: 'Enter a summary',
    add_specialist_skill: 'Add specialist skill',
    edit_specialist_skill: 'Edit specialist skill',
    enter_skill: 'Enter a skill',
    skill: 'Skill',
    poficiency: 'Proficiency',
    delete_skill: 'Delete skill',
    add_other_skill: 'Add other skill',
    edit_other_skill: 'Edit other skill',
    language: 'Language',
    add_language: 'Add language',
    edit_language: 'Edit language',
    enter_language: 'Enter a language',
    add_site_company: 'Add site company',
    edit_site_company: 'Edit site company',
    add_hobbies: 'Add hobbies',
    edit_hobbies: 'Edit hobbies',
    add_social_link: 'Add social link',
    edit_social_link: 'Edit social link',
    type: 'Type',
    type_social_links: 'Type of social links',
    type_site_company: 'Type of website',
    hobby: 'Hobby',
    enter_hobby: 'Enter a hobby',
    link: 'Link',
    enter_link: 'Enter a link',
    delete_social_link: 'Delete link',
    delete_site_company: 'Delete site',
    delete_hobby: 'Delete hobby',
    delete_language: 'Delete language',
    add_education: 'Add Education',
    add_new_education: 'Add new Education',
    edit_education: 'Edit Education',
    delete_education: 'Delete education',
    school: 'School',
    degree: 'Degree',
    field_study: 'Field of study',
    start_date: 'Start date',
    end_date: 'End date',
    description: 'Description',
    media: 'Media',
    school_name: 'School name',
    enter_description: 'Enter a description',
    upload: 'Upload',
    link: 'Link',
    media: 'Media',
    current_work: 'I currently work in this role',
    add_experience: 'Add experience',
    add_new_experience: 'Add new Experience',
    edit_experience: 'Edit experience',
    title: 'Title',
    enter_title: 'Enter a title',
    employment_type: 'Employment type',
    level_type: 'Level',
    enter_company_name: 'Enter a company name',
    company_name: 'Company name',
    delete_experince: 'Delete experience',
    add_current_position: 'Add current position',
    edit_current_position: 'Edit current position',
    delete_current_position: 'Delete current position',
    delete: 'Delete',
    add_industrial_knowledge: 'Add industrial knowledge',
    edit_industrial_knowledge: 'Edit industrial knowledge',
    industry_ex: 'Industry (ex: Web Designer)',
    skill_and_endor: 'Skills',
    network: 'Network',
    account_info: 'Account info',
    full_name: 'Full name',
    username: 'Username',
    email: 'Email',
    phone_number: 'Phone number',
    password: 'Password',
    edit: 'Edit',
    summary_done: 'This section is complete. View on\nprofile',
    cancel: 'Cancel',
    choose_from: 'Choose from the gallery',
    take_photo: 'Take a photo',
    poficiency: 'Proficiency',
    delete_skill: 'Delete skill',
    add_other_skill: 'Add other skill',
    edit_other_skill: 'Edit other skill',
    language: 'Language',
    add_language: 'Add language',
    edit_language: 'Edit language',
    enter_language: 'Enter a language',
    add_site_company: 'Add site company',
    edit_site_company: 'Edit site company',
    add_hobbies: 'Add hobbies',
    edit_hobbies: 'Edit hobbies',
    add_social_link: 'Add social link',
    edit_social_link: 'Edit social link',
    type: 'Type',
    type_social_links: 'Type of social links',
    type_site_company: 'Type of website',
    hobby: 'Hobby',
    enter_hobby: 'Enter a hobby',
    link: 'Link',
    enter_link: 'Enter a link',
    delete_social_link: 'Delete link',
    delete_site_company: 'Delete site',
    delete_hobby: 'Delete hobby',
    delete_language: 'Delete language',
    add_education: 'Add Education',
    edit_education: 'Edit Education',
    delete_education: 'Delete education',
    school: 'School',
    degree: 'Degree',
    field_study: 'Field of study',
    start_date: 'Start date',
    end_date: 'End date',
    description: 'Description',
    media: 'Media',
    school_name: 'School name',
    enter_description: 'Enter a description',
    upload: 'Upload',
    link: 'Link',
    media: 'Media',
    current_work: 'I currently work in this role',
    add_experience: 'Add experience',
    edit_experience: 'Edit experience',
    level_experience: 'Experience level',
    title: 'Title',
    enter_title: 'Enter a title',
    employment_type: 'Employment type',
    enter_company_name: 'Enter a company name',
    company_name: 'Company name',
    current_role: 'I currently work in this role',
    delete_experince: 'Delete experience',
    add_current_position: 'Add current position',
    edit_current_position: 'Edit current position',
    delete_current_position: 'Delete current position',
    delete: 'Delete',
    add_industrial_knowledge: 'Add industrial knowledge',
    edit_industrial_knowledge: 'Edit industrial knowledge',
    industry_ex: 'Industry (ex: Web Designer)',
    skill_and_endor: 'Skills',
    network: 'Network',
    account_info: 'Account info',
    full_name: 'Full name',
    username: 'Username',
    email: 'Email',
    phone_number: 'Phone number',
    password: 'Password',
    edit: 'Edit',
    summary_done: 'This section is complete. View on\nprofile',
    cancel: 'Cancel',
    choose_from: 'Choose from the gallery',
    take_photo: 'Take a photo',
    old_price: 'old price',
    new_price: 'new price',
    contact_price: 'Contact price',
    contact_profile_info: 'Contact info',
    scav: 'scav',
    successful_rate: 'Successful rate',
    cont: 'Cont. / mth',
    trusted: 'Trusted',
    contact_info: 'Contact information',
    input_phone: 'Add your phone number',
    confirm_info: 'Comfirm Infomation',
    confirm_info_desc:
      'Please choose 1 of 2 methods of providing information, this option can only be selected 1 time',
    noti_option_1: 'Notify when an employer viewed\nmy profile',
    noti_option_2: 'No notification',
    edit_profile: 'Edit profile',
    my_network: 'My Networks',
    connected: 'Connected',
    trust_connect: '{{name}} verified',
    profile_nowallet: "In case you don't see the info, please connect your wallet",
    add_new_skills: 'Add new skills',
    done: 'Done',
    contact: 'Contact',
    add_new_contact: 'Add new contact',
    info_price: '-  Info price:',
    profile_request: 'Profile request',
    experience_endorsements: 'Experience & Endorsements',
    skills_endorsements: 'Skills & Endorsements',
    connect_network: 'Connect Network',
    unlock_info: 'Unlock Info',
    notification: 'Notification',
    no_coin: 'Your balance is not enough to complete this transaction. Please top up your wallet!',
    top_up_now: 'Top up now',
    transaction_unlock_info: 'Transaction Unlock info',
    complete: 'Complete',
    transaction_code: 'Transaction code',
    time: 'Time',
    fund: 'Fund',
    wallet_balance: 'Wallet balance',
    i_got_it: 'I Got It',
    please_waitting_confirm: 'Please wait for confirmation from',
    cancel_request: 'Cancel request',
    waiting: 'Waiting',
    miss_experience: 'Please update your experience',
    miss_education: 'Please update your education',
    miss_summary: '"about.summary" is required',
    cancel_network_request: 'Cancel Network Request',
    connected: 'Connected',
    upload_media_error: 'Please upload least 1 item!'
  },
  wallet: {
    wallet_setup: 'Wallet Setup',
    wallet_create: 'Create Wallet',
    import_or_create: 'Import an existing wallet or create a\nnew one',
    import_seed: 'Import using Seed Phrase',
    create_password: 'Create\nPassword',
    password_unlock: 'This password will unlock your Dehr wallet\nonly on this service',
    new_password: 'New Password',
    confirm_password: 'Confirm Password',
    password_can_not_recover:
      'By clicking Create Password, you understand that\nDehr cannot recover this password for your\nLearn more',
    create_password_btn: 'Create password',
    secure_wallet: 'Secure\nyour Wallet',
    secure_wallet_des_1: 'Don’t risk losing your funds. protect your wallet by saving your ',
    seed_phrase_des: 'seed phrase',
    secure_wallet_des_2:
      ' in a place you trust. It’s the only way to recover your wallet if you get locked out of the app or get a new device.',
    start: 'Start',
    remind_later: 'Remind me later',
    use_seed_phrase: 'Use Seed Phrase to secure your wallet',
    why_important: 'Why is important?',
    tuto_1: 'Write down your seed phrase on a\ndehr of paper and store in a safe\nplace.',
    security_lever: 'Security lever:',
    very_strong: 'Very strong',
    risks_are: 'Risks are:',
    you_lose: '• You lose it',
    you_forgot: '• You forgot where you put it',
    someone_finds: '• Someone else finds it',
    other_option: 'Other options: Doesn’t have to be paper!',
    tips: 'Tips',
    store_bank: '• Store in bank vault',
    store_safe: '• Store in a safe',
    store_multiple: '• Store in multiple secret places',
    next: 'Next',
    write_seed_phrase: 'Write Your\nSeed Phrase',
    write_seed_phrase_des:
      'This is your seed phrase. Write it down on\na paper and keep it in a safe place. You’ll\nbe asked to re-enter this phrase (in order)\non the next step.',
    continue: 'Continue',
    tap_to_reveal: 'Tap to reveal your seed phrase',
    make_sure_no_one: 'Make sure no one is watching your screen',
    confirm_secure: 'Confirm\nSeed Phrase',
    select_word: 'Select each word in the order it was\npresented to you',
    congratulations: 'Congratulations',
    protect_success:
      'You’ve successfully protected your wallet. Remember to keep your seed phrase safe, it’s your responsibility!',
    leave_a_hint: 'Leave yourself a hint?',
    leave_a_hint_des:
      'DeHR cannot recover your wallet password\nin case you lose it.  You can find your\nseedphrase in Setting > Security & Privacy',
    learn_more: 'Learn rore',
    import_from_seed: 'Import\nFrom Seed',
    seed_phrase: 'Seed phrase',
    import: 'Import',
    term_condition: 'By proceeding, you agree to these\nTerm and Conditions',
    dehr_kyc: 'DeHR KYC Wallet',
    dehr_kyc_des: 'Set up DeHR KYC Wallet to deposit,\nwithdraw your DeHR',
    kyc_now: 'KYC now',
    enter_phone: 'Enter your\nphone number',
    enter_phone_des: 'Enter the phone address associated with\nyour account',
    choose_country: 'Choose country',
    phone: 'Phone',
    confirm: 'Confirm',
    verify_phone: 'Verify your\nphone number',
    verify_phone_des: 'Please enter the 6 digit code sent to',
    resend_code: 'Resend code',
    fill_information: 'Fill in\nyour information',
    first_name: 'First name',
    last_name: 'Last name',
    gender: 'Gender',
    passport_id: 'Passport ID',
    male: 'Male',
    female: 'Female',
    front_passport: 'Front of Passport',
    passport_information: 'Passport information',
    your_selfie: 'Your selfie photo',
    upload_photo: 'Upload photo',
    verifying: "We're verifying\nyour documents",
    take_48h: 'It takes up to 48hrs to verify your\ndocuments. Please be patient.',
    back_to_wallet: 'Back to Wallet',
    wallet: 'Wallet',
    deposit: 'Receive',
    exchange: 'Exchange',
    send: 'Send',
    jobs: 'Jobs',
    withdraw: 'Withdraw',
    sent: 'Sent',
    latest_transactions: 'Recent transactions',
    points: 'Points',
    balance: 'Balance',
    transaction_receipt: 'Transaction receipt',
    type: 'Type',
    deposited: 'Received',
    received: 'Received',
    sent: 'Sent',
    withdrawn: 'Withdrawn',
    exchanged: 'Exchanged',
    transaction_code: 'Transaction code',
    time: 'Time',
    fund: 'Fund',
    from: 'From',
    to: 'To',
    dehr_wallet: 'DeHR Wallet',
    point_Wallet: 'Point Wallet',
    wallet_balance: 'Wallet balance',
    got_it: 'I got it',
    my_dehr: 'My DeHR',
    withdraw_my_dehr: 'Withdraw my DeHR',
    what_is_seed_phrase: 'What is a ‘Seed phrase’?',
    what_is_seed_phrase_des:
      'A seed phrase is a set of twelve words that\ncontains all the information about your\nwallet, including your funds. It’s like a\nsecret code used to access your entire\nwallet.\nYou must keep your seed phrase secret\nand safe. If someone gets your seed\nphrase, they’ll gain control over your\naccounts.\nSave it in a place where only you can\naccess it. If you lose it, not even Dehr\ncan help you recover it.',
    skip_security: 'Skip Account Security',
    skip_security_des:
      'I understand that if I lose my seed phrase, I will not be able to access my wallet',
    secure_now: 'Secure now',
    skip: 'Skip',
    setup_wallet: 'Please setup Wallet first!',
    address_wallet: 'Wallet Address',
    history: 'History',
    transactions: 'Transactions',
    address_wallet_error:
      'The wallet address does not match the old wallet, you will not be able to transact!',
    expire_contact_price: 'Edit Price will be available after:\n{{time}}',
    address_for_account: 'Address for account',
    from_sender: 'From {{name}}',
    to_receiver: 'To {{name}}',
    copied: 'Copied to clipboard',
    amount: 'Amount',
    password: 'Password',
    kyc_verify: 'Please verify KYC first!'
  },
  mission: {
    mission: 'Mission',
    all_missions: 'All missions',
    referral: 'Referral',
    reward: 'Reward',
    do_it: 'Do it',
    verify_it: 'Verify it',
    in_progress: 'In progress',
    get_reward: 'Get reward',
    date: 'Date',
    requirements: 'Requirements',
    req_1:
      'Lorem ipsumLorem ipsum dolor sit amet,\nconsectetur adipiscing elit. Dolor sit amet,\nconsectetur',
    req_2: 'Lorem ipsumLorem ipsum dolor sit amet',
    req_3: 'Dolor sit amet, consectetur',
    req_4: 'Lorem ipsumLorem ipsum dolor sit amet,\nconsectetur adipiscing elitolor sit',
    work_with_you: '{{name}} work with you in {{company_name}}',
    what_department: 'What department do you work in?',
    marketing: 'Marketing',
    technical: 'Technical',
    hr: 'Human Resource',
    complete: 'Complete',
    referral_link: 'Referral link',
    share: 'Share',
    referral_id: 'Referral ID',
    copy: 'copy',
    scan_qr_code: 'Scan QR code',
    suggestion: 'Suggestion',
    joined_in: 'Joined in',
    invite: 'Invite',
    friends_invited: 'Friends invited',
    for_new_users: 'For new users',
    for_all_users: 'For all users',
    received: 'Received',
    check: 'Check',
    mission_not_done: "You haven't completed this quest yet.\nDo it now?",
    mission_done: 'You have completed this mission.\nGet a reward now.',
    reward_success: 'Get reward success!',
    verify_network: 'Verify a friend in your network'
  },
  home: {
    welcome_home: 'Welcome home',
    fast_search: 'Fast search',
    fast_search_des: 'You can search quickly for the job you want...',
    search: 'Search',
    matched: 'Matched',
    apply_now: 'Apply now',
    popular: 'Popular',
    featured: 'Featured',
    all: 'All',
    hot_job: 'Hot job',
    compression: 'Hot Jobs',
    people: 'People',
    freelancer: 'Freelancer',
    connect: 'Connect',
    bid_now: 'Bid now',
    update_your_skill: 'Your mached score is low, improve skill to\napply again',
    explore_peolpe: 'Explore people',
    seek_people: 'Seek for people you need to employ',
    search_with: 'Search with',
    job_posted: 'Job posted',
    see_all: 'See all',
    people_match: 'People matched your Job Posted',
    matched_profiles: 'Matched profiles',
    hiring_process: 'Hiring Process',
    contact: 'Contact',
    ignore: 'Ignore',
    reject: 'Reject',
    applied: 'Applied',
    viewed: 'Viewed',
    interview: 'Interview',
    applied_count: 'Applied ({{count}})',
    viewed_count: 'Viewed ({{count}})',
    interview_count: 'Interview ({{count}})',
    people_matched: 'People matched',
    best_for_you: 'Best for you',
    ess: 'ESS',
    learning: 'Learning',
    sponsor: 'Sponsor',
    business: 'Business',
    join: 'Join',
    years: 'years',
    question: 'Question',
    previous: 'Previous',
    class_completed: 'Classes\ncompleted',
    time_duration: 'Time\nduration',
    available_your_skill: 'Available for you skill',
    mins: 'mins',
    available_class: 'Available classses',
    last_classes: 'Last classes',
    classes: 'Classes',
    organisation: 'Organisation',
    available_to: 'Available to',
    major: 'Major',
    current_fee: 'Current fee',
    last_ranking: 'Last ranking',
    view_profile: 'View profile',
    university: 'University',
    people_sponsor: 'People Sponsor',
    notication: 'Notication',
    become_pro: 'Become a PRO user to employ people',
    switch_employer: 'Switch to your employer account',
    setting: 'Setting',
    support: 'Support',
    logout: 'Logout',
    version: 'Version',
    active_pro_account: 'Active pro account',
    summary: 'Summary',
    available: 'Available',
    stake_date: 'Stake date',
    value_date: 'Value date',
    redemption_date: 'Redemption Date',
    lock_amount: 'Lock amount',
    you_agree: 'By proceeding, you agree to',
    service_agreement: 'DeHR Staking Service Agreement',
    confirm_purchare: 'Confirm purcharse',
    dehr: 'DeHR',
    add_to_hiring: 'Add to Hiring\nProcess',
    notification: 'Notification',
    top_up: 'Top up',
    top_up_desc:
      'Your balance is not enough to complete this transaction. Please top up your wallet',
    transaction_unlock_info: 'Transaction Unlock info',
    please_waitting_confirm: 'Please wait for confirmation from @{{name}}',
    profile_views: 'Profile views',
    send: 'Your unlock info request',
    receiver: 'People wants to unlock your info',
    no_coin: 'Your balance is not enough to complete this transaction. Please top up your wallet!',
    infomation_personal: 'Infomation personal',
    name: 'Name:',
    email: 'Email:',
    phone: 'Phone:',
    close: 'Close',
    farm: 'Farm',
    join_now: 'Join now',
    full_time: 'Full time',
    part_time: 'Part time',
    hot: 'Hot',
    latest: 'Latest',
    jobs: 'Jobs',
    hot_jobs: 'Hot Jobs',
    apply_now: 'Apply now',
    applicants: 'applicants',
    done: 'Done',
    ongoing: 'Ongoing',
    pending: 'Pending'
  },
  search: {
    advance: 'Advance searching',
    advance_title: 'Advance fliter',
    advance_sort: 'Sort by',
    advance_relevant: 'Most relevant',
    advance_recent: 'Recent',
    advance_date: 'Date posted',
    advance_date_any_time: 'Anytime',
    advance_date_past_month: 'Past month',
    advance_date_past_week: 'Past week',
    advance_date_past_24: 'Past 24 hours',
    advance_industry: 'Industry',
    advance_industry_search: 'Industry (ex: Web Designer)',
    advance_experience: 'Experience Level',
    advance_job_type: 'Job type',
    advance_location: 'Location',
    advance_location_search: 'Location (ex: Ho Chi Minh City, Vietnam)',
    advance_salary: 'Salary',
    advance_max: 'Max',
    advance_contact_price: 'Contact price',
    advance_reset: 'Reset',
    advance_search_now: 'Search now',
    advance_option: 'Choose your option'
  },
  jobs: {
    recommend: 'Recommend',
    posted_jobs: 'Posted Jobs',
    applied_jobs: 'Applied Jobs',
    welcome_home: 'Welcome Home',
    applicants: 'applicants',
    job_description: 'Job Description',
    requirement: 'Requirement',
    viewers: 'viewers',
    post_your_jobs: 'Post Your Jobs',
    title_job: 'Title job',
    company_name: 'Company Name',
    location: 'Location',
    job_type: 'Job type',
    experience_level: 'Experience Level',
    salary: 'Salary',
    job_description: 'Job Description',
    other_benefits: 'Other benefits',
    job_requirement: 'Job requirement',
    apply_now: 'Apply now',
    edit_this_job: 'Edit this job',
    show: 'Show',
    applied: 'applied',
    cancel: 'cancel',
    post_now: 'Post now',
    see_all: 'See All'
  }
};
